---
title: "SMUT mediation try"
output: html_document
date: "2024-05-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
rm(list = ls())

```

# Load libraries
```{r}
library(SMUT)
library(tidyverse)
library(here)
```



```{r}
library(SMUT)
dim(Genotype_data)
#> [1] 100 200
Genotype_data[1:3,1:4]
#>              SNP_1 SNP_2 SNP_3 SNP_4
#> Individual_1     0     2     1     0
#> Individual_2     1     1     0     0
#> Individual_3     1     1     0     1
Genotype_data_2 = Genotype_data[ , 1, drop = FALSE]
Genotype_data_2 %>% class()
```


```{r}
N_individual = nrow(Genotype_data)
N_SNPs = ncol(Genotype_data)

set.seed(1)

# generate two covariates
covariate_1=rnorm(nrow(Genotype_data),0,1)
covariate_2=sample(c(0,1),size=nrow(Genotype_data),replace = TRUE)
covariates=cbind(covariate_1,covariate_2)
covariates %>% head()

```


```{r}
# generate coefficients: iota_M, iota_Y, beta, theta and gamma
iota_M = c(0.3,0.5)
iota_Y = c(0.2,0.6)
beta = rnorm(N_SNPs, 1, 2)
theta = 1.2
gamma = rnorm(N_SNPs, 0.5, 2)

# generate error terms
e1 = rnorm(N_individual, 0, 1)
e2 = rnorm(N_individual, 0, 1)
```


```{r}
# generate the mediator
mediator = 1 + covariates %*% iota_M + Genotype_data %*% beta + e1
mediator %>% head()

```


```{r}
# generate the outcome
outcome = 2 + mediator*theta + covariates %*% iota_Y + Genotype_data %*% gamma + e2
outcome %>%  head()

class(outcome)
```


```{r}
# generate the binary outcome 
eta = 2 + mediator*theta + covariates %*% iota_Y + Genotype_data %*% gamma
pi = 1/(1+exp( -(eta ) ))
binary_outcome = rbinom(length(pi),size=1,prob=pi) %>% as.logical()
binary_outcome
```




```{r}
result_binary = SMUT(G = Genotype_data_2,
                      mediator = mediator,
                      outcome = binary_outcome,
                      # covariates = covariates,
                      outcome_type = "binary")
result_binary
```
```{r}

```

